### ISSUE TITLE
Order of Magnitude Difference in Generated Optical Flow

### ISSUE THREAD

**Issue by TouqeerAhmad** [google-research/opticalflow-autoflow#3]
Hello, 

I have been playing around with the shared models in the repo, and compared the raft_it_ft/raft_it_pre models against origin [RAFT](https://github.com/princeton-vl/RAFT) repo. I am seeing an order of magnitude difference between the original RAFT and provided models for the same set of images. I understand numerically there would be different in computed optical flow, but I did not expect the difference be one order of magnitude. I was wondering if you have noticed any such anomaly. 

Thanks!

**Comment by autoflow-google** [comment]
Hi Touqeer,

I think this is likely due to the FLOW_SCALE_FACTOR of 20 -- where the model produces flow * FLOW_SCALE_FACTOR. This is an artifact from the PWC-Net training code and should be "fixed" by just diving the output flow by 20.

Please let me know if that solves the problem.

Best,
Charles

**Comment by Sino0904** [comment]
Hello @autoflow-google 
I am still seeing the same issue. On the same video, for pixels that should have displacements of around 20 pixels (using the original RAFT method), the new flow has closer to 1 pixel displacement. Do you know why this might be happening?

**Comment by autoflow-google** [comment]
It's due to a change in the FLOW_SCALE_FACTOR. Please divide the flow by 20.

**Comment by Sino0904** [comment]
Thank you for responding so quickly. I did exactly that, but that makes the magnitude of the flow even smaller. When I multiplied the flow by 20 the flow output from new RAFT model was in the same ballpark as the original flow. So I wanted to confirm if it should be multiplication or division and whether we should always use 20 as the scale factor.

**Comment by autoflow-google** [comment]
Oh, yes, sorry. Multiply by 20 should work.

**Comment by autoflow-google** [comment]
The TF-RAFT code uses this:

return upsampled_flow_preds[-1]/self.flow_scale_factor

where self.flow_scale_factor is a constant = 20.

So multiply should cancel this out.
